print('hello world')
print('hello vai')
print('ok vai')
print('bye vai')
print('thank you vai')
print('nice vai')
print('jaki good')
print('jaki sleep')
print('i love you')
print('no')
print('bye then')